### ISSUE TITLE
Webback compiles with warnings

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/CMYG#3]
Just after the clone of the repo, in the `Angular-CoEvents` folder, after running `npm install`, when running `ng serve -o` I get a lot of css warnining like this:

```
WARNING in ./src/app/events/event/event.component.css
(Emitted value instead of an instance of Error) postcss-custom-properties: /Users/claudio/Documents/Insegnante/Born2Code/github/CMYG/Angular-CoEvents/src/app/events/event/event.component.css:22:3: variable '--dirty-white' is undefined and used without a fallback
NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-properties: /Users/claudio/Documents/Insegnante/Born2Code/github/CMYG/Angular-CoEvents/src/app/events/event/event.component.css:22:3: variable '--dirty-white' is undefined and used without a fallback
    at Object.emitWarning (/Users/claudio/Documents/Insegnante/Born2Code/github/CMYG/Angular-CoEvents/node_modules/webpack/lib/NormalModule.js:117:16)
    at /Users/claudio/Documents/Insegnante/Born2Code/github/CMYG/Angular-CoEvents/node_modules/postcss-loader/index.js:131:24
    at Array.forEach (<anonymous>)
    at /Users/claudio/Documents/Insegnante/Born2Code/github/CMYG/Angular-CoEvents/node_modules/postcss-loader/index.js:130:31
    at <anonymous>
 @ ./src/app/events/event/event.component.ts 39:21-53
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

Please resolve these warnings or add documentation about how to resolve them.

**Comment by ghost** [comment]
## postcss-custom-properties issue

At the moment we can't disable the warnings without editing the webpack config of angular-cli.
Those warnings, once compiled or during develop mode doesn't affect the project as the browser render it fine.

Those warnings are because angular do a bundle for the "style.css" in the root of the project and another one for all the component.

As my css var are into the style.css, when compiling webpack doesn't see the var into those component as they aren't defined on them.

More info on [Google](https://www.google.it/search?q=postcss-custom+warnings+angular&oq=postcss-custom+warnings+angular&aqs=chrome..69i57.8191j0j1&sourceid=chrome&ie=UTF-8), there are a lot of issue, feature request and other about those warnings.

**Comment by wbigger** [comment]
OK, good to know, fine for now.
